const zacetniPodatkiSkladateljev = [
    { id: "johann-sebastian-bach", name: "Johann Sebastian Bach", birth: "1685", death: "1750", bio: "Nemški skladatelj in polifonični genij. Preučeval in predeloval je koncerte, ki jih je napisal [[Antonio Vivaldi]]. Proti koncu življenja se je srečal z mladimi glasbeniki, ki jih je navdihoval tudi [[Georg Friedrich Händel]].", events: [{ id: 1, year: "1723", location: "Leipzig", text: "Postal Cantor v cerkvi sv. Tomaža." }, { id: 2, year: "1747", location: "Potsdam", text: "Napisal Glasbeno daritev za kralja." }] },
    { id: "antonio-vivaldi", name: "Antonio Vivaldi", birth: "1678", death: "1741", bio: "Beneški violinist in skladatelj, znan kot 'Rdeči duhovnik'. Razvil je obliko baročnega koncerta, ki je ključno vplivala na to, kako sta komponirala [[Johann Sebastian Bach]] in [[Georg Friedrich Händel]].", events: [{ id: 3, year: "1703", location: "Benetke", text: "Začne poučevati violino v Ospedale della Pietà." }, { id: 4, year: "1725", location: "Amsterdam", text: "Objavi zbirko s Štirimi letnimi časi." }] },
    { id: "georg-friedrich-haendel", name: "Georg Friedrich Händel", birth: "1685", death: "1759", bio: "Nemško-angleški skladatelj oratorijev. V Italiji je osebno spoznal mojstre, kot je bil [[Arcangelo Corelli]], kasneje pa je v Londonu tekmoval z operami, ki jih je pisal [[Giovanni Battista Pergolesi]].", events: [{ id: 5, year: "1712", location: "London", text: "Trajno se preseli v Anglijo." }, { id: 6, year: "1741", location: "Dublin", text: "Premierno uprizori oratorij Mesija." }] },
    { id: "arcangelo-corelli", name: "Arcangelo Corelli", birth: "1653", death: "1713", bio: "Italijanski violinski virtuoz in utemeljitelj žanra concerto grosso. Njegov stil igranja je bil neposredna podlaga za razvoj, ki so ga nadaljevali [[Antonio Vivaldi]], [[Georg Friedrich Händel]] in [[Henry Purcell]].", events: [{ id: 7, year: "1681", location: "Rim", text: "Objavi svojo prvo zbirko Sonate da chiesa op. 1." }] },
    { id: "claudio-monteverdi", name: "Claudio Monteverdi", birth: "1567", death: "1643", bio: "Ključni prehodni skladatelj med renesanso in barokom. Utemeljil je moderno opero. Njegovo delo je tlakovalo pot celotni generaciji italijanskih mojstrov, med katerimi je kasneje blestel [[Arcangelo Corelli]].", events: [{ id: 8, year: "1607", location: "Mantova", text: "Premierno uprizori opero L'Orfeo." }, { id: 9, year: "1613", location: "Benetke", text: "Imenovan za maestro di cappella v baziliki sv. Marka." }] },
    { id: "henry-purcell", name: "Henry Purcell", birth: "1659", death: "1695", bio: "Največji angleški baročni skladatelj. V svojem delu je združeval francoske stilistične elemente, ki jih je uveljavil [[Jean-Baptiste Lully]], in italijanski slog, ki ga je širil [[Arcangelo Corelli]].", events: [{ id: 10, year: "1679", location: "London", text: "Postane organist v Westminstrski opatiji." }, { id: 11, year: "1689", location: "London", text: "Prva izvedba opere Didona in Enej." }] },
    { id: "jean-baptiste-lully", name: "Jean-Baptiste Lully", birth: "1632", death: "1687", bio: "V Italiji rojen francoski dvorni skladatelj kralja Ludvika XIV. Ustvaril je francosko operno tradicijo, njegov orkestrski stil pa je močno vplival na nemške avtorje, predvsem na to, kako je pisal [[Johann Sebastian Bach]].", events: [{ id: 12, year: "1653", location: "Pariz", text: "Imenovan za kraljevega skladatelja instrumentalne glasbe." }] },
    { id: "francois-couperin", name: "François Couperin", birth: "1668", death: "1733", bio: "Slavni francosko dvorni skladatelj in organist. Zelo je občudoval italijanski slog in je v svojih delih poskušal združiti stile, ki sta jih zagovarjala [[Jean-Baptiste Lully]] in [[Arcangelo Corelli]].", events: [{ id: 13, year: "1693", location: "Versailles", text: "Postane kraljevi organist Ludvika XIV." }] },
    { id: "giovanni-battista-pergolesi", name: "Giovanni Battista Pergolesi", birth: "1710", death: "1736", bio: "Italijanski skladatelj, ki je kljub izjemno kratkemu življenju napisal ključna dela zgodnjega klasicizma. Njegova komična opera je sprožila debate v Parizu, kjer so sicer cenili tradicijo, ki jo je postavil [[Jean-Baptiste Lully]].", events: [{ id: 14, year: "1733", location: "Neapelj", text: "Premiera operne medigre Služabnica gospodarica." }, { id: 15, year: "1736", location: "Pozzuoli", text: "Tik pred smrtjo dokonča pretresljivi Stabat Mater." }] },
    { id: "heinrich-schuetz", name: "Heinrich Schütz", birth: "1585", death: "1672", bio: "Najpomembnejši nemški skladatelj pred Bachom. V Benetkah je študiral neposredno v obdobju, ko je tam deloval [[Claudio Monteverdi]], in je italijanski monodični slog prenesel v nemški protestantski prostor.", events: [{ id: 16, year: "1615", location: "Dresden", text: "Prevzame vodenje dvorne kapele (Kapellmeister)." }] }
];
