const zacetniPodatkiSkladateljev = [
    {
        "id": "annibale-padovano",
        "name": "Annibale Padovano",
        "birth": "1527",
        "death": "1575",
        "img": "",
        "events": [
            { "id": 1, "year": "1527", "location": "Padova", "text": "Rojstvo" },
            { "id": 2, "year": "1545", "location": "Gradec", "text": "Zaposlitev kot organist na dvoru nadvojvode Karla II." },
            { "id": 3, "year": "1546", "location": "Gradec", "text": "Napredovanje v glavnega glasbenika na dvoru" },
            { "id": 4, "year": "1552", "location": "Benetke", "text": "Zaposlitev kot organist v baziliki sv. Marka" },
            { "id": 5, "year": "1556", "location": "Benetke", "text": "Izid zbirke 'Il primo libro de ricercari a 4'" },
            { "id": 6, "year": "1561", "location": "Benetke", "text": "Izid zbirke 'Di Cipriano et Annibale madrigali'" },
            { "id": 7, "year": "1564", "location": "Benetke", "text": "Izid zbirke 'Il primo libro de madrigali'" },
            { "id": 8, "year": "1565", "location": "Benetke", "text": "Zaključek službovanja kot organist v baziliki sv. Marka" },
            { "id": 9, "year": "1567", "location": "Benetke", "text": "Izid zbirke 'Liber motectorum'" },
            { "id": 10, "year": "1568", "location": "", "text": "Komponiranje glasbe za poroko vojvode Viljema V. Bavarskega in Renate Lotarinške z [[Orlande de Lassus]]" },
            { "id": 11, "year": "1570", "location": "Gradec", "text": "Prevzem naziva direktorja glasbe" },
            { "id": 12, "year": "1571", "location": "", "text": "Komponiranje skladbe 'Dialogo a 7' v čast nadvojvodi Karlu in Marije Bavarski" },
            { "id": 13, "year": "1573", "location": "Benetke", "text": "Izid zbirke 'Il primo libro delle messe'" },
            { "id": 14, "year": "1575", "location": "Gradec", "text": "Smrt" }
        ]
    },
    {
        "id": "orlande-de-lassus",
        "name": "Orlande de Lassus",
        "birth": "1532",
        "death": "1594",
        "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Orlande_de_Lassus.jpg/960px-Orlande_de_Lassus.jpg",
        "events": [
            { "year": "1532", "location": "Mons", "text": "Rojstvo." },
            { "year": "1544", "location": "", "text": "Zaposlitev v službi Ferranteja Gonzage." },
            { "year": "1545", "location": "Mantova", "text": "Bivanje na dvoru v Mantovi." },
            { "year": "1546", "location": "Milano", "text": "Bivanje v Milanu." },
            { "year": "1549", "location": "Neapelj", "text": "Prihod v Neapelj in neformalna zaposlitev pri Constantinu Castriotu." },
            { "year": "1551", "location": "Rim", "text": "Prihod v Rim." },
            { "year": "1553", "location": "Rim", "text": "Zaposlitev kot kapelnik v baziliki sv. Janeza v Lateranu." },
            { "year": "1554", "location": "Antwerpen", "text": "Prihod v Antwerpen." },
            { "year": "1555", "location": "Antwerpen", "text": "Izid zbirke madrigalov, vilanesk, francoskih canzon in motetov." },
            { "year": "1555", "location": "Benetke", "text": "Izid prve knjige petglasnih madrigalov." },
            { "year": "1555", "location": "Rim", "text": "Komponiranje maše 'Missa Domine secundum actum meum'." },
            { "year": "1555", "location": "Rim", "text": "Komponiranje zbirke 'Sacrae lectiones novem ex propheta Iob'." },
            { "year": "1556", "location": "Antwerpen", "text": "Izid prve knjige pet- in šestglasnih motetov." },
            { "year": "1556", "location": "München", "text": "Sprejetje vabila na dvor vojvode Albrehta V." },
            { "year": "1556", "location": "München", "text": "Zaposlitev kot tenorist v dvorni kapeli." },
            { "year": "1558", "location": "", "text": "Poroka z Regino Wäckinger." },
            { "year": "1560", "location": "", "text": "Rojstvo sina Ferdinanda." },
            { "year": "1560", "location": "", "text": "Komponiranje zbirke 'Prophetiae Sibyllarum'." },
            { "year": "1562", "location": "Praga", "text": "Prisotnost na kronanju nadvojvode Maksimilijana za češkega kralja." },
            { "year": "1562", "location": "Frankfurt", "text": "Prisotnost na ustoličenju nadvojvode Maksimilijana za kralja Rimljanov." },
            { "year": "1563", "location": "", "text": "Rojstvo sina Rudolfa." },
            { "year": "1563", "location": "München", "text": "Prevzem vodenja dvorne kapele kot kapelnik." },
            { "year": "1565", "location": "", "text": "Izid zbirke 'Sacrae lectiones novem ex propheta Iob'." },
            { "year": "1567", "location": "", "text": "Izid četrte knjige petglasnih madrigalov." },
            { "year": "1568", "location": "München", "text": "Sodelovanje pri poročnih slovesnostih Wilhelma V. in Renée Lotarinške z [[Annibale Padovano]]." },
            { "year": "1568", "location": "München", "text": "Nastopanje v vlogi magnifica v italijanski commedia dell’arte." },
            { "year": "1570", "location": "", "text": "Podelitev plemiškega naziva s strani Maksimilijana II." },
            { "year": "1570", "location": "", "text": "Začetek izida petih zvezkov sakralnih del 'Patrocinium musices'." },
            { "year": "1571", "location": "", "text": "Obisk francoskega dvora na povabilo Karla IX." },
            { "year": "1573", "location": "", "text": "Ponoven obisk francoskega dvora na povabilo Karla IX." },
            { "year": "1574", "location": "", "text": "Tretji obisk francoskega dvora na povabilo Karla IX." },
            { "year": "1574", "location": "Rim", "text": "Povišanje v viteza Zlate ostroge s strani papeža Gregorja XIII." },
            { "year": "1594", "location": "München", "text": "Smrt." }
        ]
    }
];